### ISSUE TITLE
cannot open pictures saved by function 'saveAsMapImage' 

### ISSUE THREAD

**Issue by CodeToPoem** [marinaKollmitz/lattice_planner#1]
Hi
When I want to see the dynamic costmaps, I use function 'saveTimedCostmaps' in 'dynamic_social_layers.cpp'. After that I see the png files but I cannot open these files. Do you have any ideas about it?

**Comment by marinaKollmitz** [comment]
Hi, thank you for pointing it out, the file extension has to be .pgm not .png. I corrected it in the code of https://github.com/marinaKollmitz/human_aware_navigation/commit/2408edbe9de421745ab498dcaa3971ad3f061dd7. I hope you can see the dynamic cost maps now.

**Comment by CodeToPoem** [comment]
Now I can see the costmaps. Thanks a lot.
