### ISSUE TITLE
Support for ROS Melodic?

### ISSUE THREAD

**Issue by marcuskohtongjie95** [marinaKollmitz/lattice_planner#2]
Hi Marina,
I am trying to integrate your lattice planner (alongside the entire human aware navigation package) into my current project which runs on ROS Melodic and porting issues (since it's originally written for ROS Indigo) have been a headache as I just started learning ROS. As it is a shared project with many other researchers, running in ROS Indigo is not quite an option.

Wonder if this package has support for ROS Melodic or do you have any tips that you can share? I would gladly appreciate it.
Regards,
Marcus

**Comment by marinaKollmitz** [comment]
Hi Marcus, 
I am not actively using this code at the moment, thats why it is taking a bit. I am on it to make it work for melodic. Give me a few days.
Best,
Marina

**Comment by marinaKollmitz** [comment]
Hi Marcus, 
I updated the code for melodic. Please look at the [human_aware_navigation wiki](https://github.com/marinaKollmitz/human_aware_navigation/wiki) to check how to get the melodic code and run the framework with toy example. I hope everything works out, please test it and close the issue if it all works as expected. If you run into problems, let me know. 
Best,
Marina
